name: pedrolemoz
description: pedrolemoz.github.io
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  unicons: ^2.1.0
  url_launcher: ^6.1.9

flutter:
  uses-material-design: true