name: pedrolemoz
description: pedrolemoz.github.io
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animations: ^2.0.7
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  unicons: ^2.1.0
  url_launcher: ^6.1.9

dev_dependencies:
  flutterando_analysis: ^0.0.2

flutter:
  uses-material-design: true
